USE [master]
GO

/****** Object:  Database [LotteryRecord]    Script Date: 2016/8/20 18:28:27 ******/
CREATE DATABASE [LotteryRecord]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'LotteryRecord', FILENAME = N'D:\SqlDatabase\LotteryRecord.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'LotteryRecord_log', FILENAME = N'D:\SqlDatabase\LotteryRecord_log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [LotteryRecord] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [LotteryRecord].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [LotteryRecord] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [LotteryRecord] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [LotteryRecord] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [LotteryRecord] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [LotteryRecord] SET ARITHABORT OFF 
GO

ALTER DATABASE [LotteryRecord] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [LotteryRecord] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [LotteryRecord] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [LotteryRecord] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [LotteryRecord] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [LotteryRecord] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [LotteryRecord] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [LotteryRecord] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [LotteryRecord] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [LotteryRecord] SET  DISABLE_BROKER 
GO

ALTER DATABASE [LotteryRecord] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [LotteryRecord] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [LotteryRecord] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [LotteryRecord] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [LotteryRecord] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [LotteryRecord] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [LotteryRecord] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [LotteryRecord] SET RECOVERY FULL 
GO

ALTER DATABASE [LotteryRecord] SET  MULTI_USER 
GO

ALTER DATABASE [LotteryRecord] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [LotteryRecord] SET DB_CHAINING OFF 
GO

ALTER DATABASE [LotteryRecord] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [LotteryRecord] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [LotteryRecord] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [LotteryRecord] SET  READ_WRITE 
GO


